=== Suhana-shakya/XML-lab/Number9c.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="main_heading" type="xs:string"/>
        <xs:element name="category" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="item" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Suhana-shakya/XML-lab/Number9a.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Number9b.xsl"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Number9c.xsd">
  <main_heading>Hello Everyone! Welcome to XML to CSS</main_heading>
  <category>
    <title>Algo</title>
    <item>Greedy Algo</item>
    <item>Ramdomised Algo</item>
    <item>Searching Algo</item>
    <item>Sorting Algo</item>
  </category>
  <category>
    <title>Data Structures</title>
    <item>Stack</item>
    <item>Queue</item>
    <item>Linked List</item>
  </category>
  <category>
    <title>Web Technology</title>
    <item>HTML</item>
    <item>CSS</item>
    <item>Java Script</item>
    <item>PHP</item>
  </category>
  <category>
    <title>Languages</title>
    <item>C/C++</item>
    <item>Java</item>
    <item>Python</item>
    <item>Ruby</item>
  </category>
  <category>
    <title>DBMS</title>
    <item>Basics</item>
    <item>ER Diagram</item>
    <item>Normalization</item>
    <item>Transaction Concepts</item>
  </category>
</root>
