=== Suhana-shakya/XML-lab/Number5a.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="first_name" type="xs:string"/>
                    <xs:element name="middle_name" type="xs:string" minOccurs="0"/>
                    <xs:element name="last_name" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="email">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="phone">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="9[7-8]\d{8}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="address" maxOccurs="2">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="type" use="required">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="permanent"/>
                          <xs:enumeration value="temporary"/>
                        </xs:restriction>
                      </xs:simpleType>
                      </xs:attribute>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="DOB" maxOccurs="2">
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:date">
                    <xs:attribute name="type" use="required">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="AD"/>
                          <xs:enumeration value="BS"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:attribute>
                  </xs:extension>
                </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="roll" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Suhana-shakya/XML-lab/Number5.xml
<?xml version="1.0" encoding="UTF-8"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Suhana\Lab Report2\Number5a.xsd">
  <student roll="m12">
    <name>
      <first_name>Nirjala</first_name>
      <middle_name>Ale</middle_name> 
      <last_name>Magar</last_name>
    </name>
    <email>nirjala@gmail.com</email>
    <phone>9726154764</phone>
    <address type="permanent">Syangja</address>
    <address type="temporary">Tokha</address>
    <DOB type="AD">2006-02-20</DOB>
    <DOB type="BS">2062-11-08</DOB>
  </student>
</students>
