=== Suhana-shakya/XML-lab/Number7a.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="movies">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="movie" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="year" type="xs:string"/>
              <xs:element name="director">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="name" type="xs:string" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:choice maxOccurs="unbounded">
                <xs:element name="comment">
                  <xs:complexType>
                    <xs:simpleContent>
                      <xs:extension base="xs:string">
                        <xs:attribute name="lang" type="xs:string" use="optional"/>
                      </xs:extension>
                    </xs:simpleContent>
                  </xs:complexType>
                </xs:element>
                <xs:element name="newcomment" type="xs:string"/>
              </xs:choice>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Suhana-shakya/XML-lab/Number7.xml
<?xml version="1.0" encoding="UTF-8"?>
<movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Suhana\Lab Report2\Number7a.xsd">
  <movie id="m23">
    <title>Hum Tum</title>
    <year>2000</year>
    <director name="Artist">Karan Johar</director>
    <comment lang="Eng"></comment>
  </movie>
  <movie id="m25">
    <title>Hum saath saath hai</title>
    <year>1990</year>
    <director name="Artist">Ajay</director>
    <comment lang="Eng">Super Movie</comment>
  </movie>
  <movie id="m20">
    <title>Hum aapke hai koun</title>
    <year>1990</year>
    <director name="Artist">Yash Raj</director>
    <newcomment>Best movie</newcomment>
  </movie>
</movies>
