=== Suhana-shakya/XML-lab/Number6a.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="university">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="school">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="location" type="xs:string"/>
            <xs:element name="staffCollection">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="staff" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="name" type="xs:string"/>
                        <xs:element name="title" type="xs:string" minOccurs="0"/>
                        <xs:element name="category">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:enumeration value="academic"/>
                              <xs:enumeration value="general"/>
                              <xs:enumeration value="technical"/>
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:element>
                        <xs:element name="address" minOccurs="0" maxOccurs="unbounded">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="street" type="xs:string"/>
                              <xs:element name="suburb" type="xs:string"/>
                              <xs:element name="postcode" type="xs:string"/>
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                      <xs:attribute name="stId" type="xs:ID" use="required"/>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="subjectCollection">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="subject" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="name" type="xs:string"/>
                        <xs:element name="description" type="xs:string"/>
                        <xs:element name="capacity">
                          <xs:simpleType>
                            <xs:restriction base="xs:integer">
                              <xs:minInclusive value="6"/>
                              <xs:maxInclusive value="400"/>
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:element>
                        <xs:element name="taughtBy" minOccurs="1" maxOccurs="unbounded">
                          <xs:complexType>
                            <xs:attribute name="staffRef" type="xs:IDREF" use="required"/>
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                      <xs:attribute name="subId" type="xs:ID" use="required"/>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="sid" type="xs:ID" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== Suhana-shakya/XML-lab/Number6.xml
<?xml version="1.0" encoding="UTF-8"?>
<university xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Suhana\Lab Report2\Number6a.xsd">
  <school sid="s9">
    <name>Shree Mahankal Secondary School</name>
    <location>Mahaboudha</location>
    <staffCollection>
      <staff stId="st8">
        <name>Rama</name>
        <category>general</category>
        <address>
          <street>Main street</street>
          <suburb>Baneshwor</suburb>
          <postcode>44600</postcode>
        </address>
        <address>
          <street>45 Lake Road</street>
          <suburb>Lakeside</suburb>
          <postcode>33700</postcode>
        </address>
      </staff>
      <staff stId="st00">
        <name>Kumar Sagar</name>
        <title>Professor</title>
        <category>academic</category>
        <address>
          <street>1245 street</street>
          <suburb>Dillibazaar</suburb>
          <postcode>440</postcode>
        </address>
      </staff>
      <staff stId="st01">
        <name>Surana Shrestha</name>
        <title>Lab Professor</title>
        <category>technical</category>
        <address>
          <street>2nd street</street>
          <suburb>Naya bazaar</suburb>
          <postcode>4400</postcode>
        </address>
      </staff>
    </staffCollection>
    <subjectCollection>
      <subject subId="sub6">
        <name>Web Technology</name>
        <description>HTML and CSS</description>
        <capacity>60</capacity>
        <taughtBy staffRef="st00"/>
      </subject>
      <subject subId="sub8">
        <name>Science</name>
        <description>Evaporation</description>
        <capacity>50</capacity>
        <taughtBy staffRef="st01"/>
      </subject>
    </subjectCollection>
  </school>
</university>
