=== Suhana-shakya/XML-lab/Number4a.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="books">
    <xs:complexType>
      <xs:sequence>
       <xs:element name="book" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="author" minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="first_name" type="xs:string"/>
                  <xs:element name="middle_name" type="xs:string"/>
                  <xs:element name="last_name" type="xs:string"/>
                </xs:sequence>
                <xs:attribute name="title" default="ms">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:enumeration value="mr"/>
                      <xs:enumeration value="mrs"/>
                      <xs:enumeration value="ms"/>
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="phone" type="xs:string"/>
                <xs:attribute name="email" type="xs:string"/>
              </xs:complexType>
            </xs:element>
            <xs:element name="page_no" type="xs:integer"/>
            <xs:element name="price">
              <xs:complexType>
                <xs:simpleContent>  
                  <xs:extension base="priceLimit">
                    <xs:attribute name="currency" use="required">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="NPR"/>
                          <xs:enumeration value="INR"/>
                          <xs:enumeration value="USD"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:attribute>
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="ISBN" type="xs:ID" use="required"/>
        </xs:complexType>
      </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="priceLimit">
    <xs:restriction base="xs:decimal">
      <xs:maxInclusive value="600"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== Suhana-shakya/XML-lab/Number4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE book[
<!ELEMENT book (title,author+,page_no,price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (name,phone,email)>
<!ELEMENT name (first_name,middle_name,last_name)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT middle_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT page_no (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST author title (mr|mrs|ms) "ms">
<!ATTLIST price currency (NPR|INR|USD) "NPR">
<!ATTLIST book ISBN ID #REQUIRED>
]>-->
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Suhana\Lab Report2\Number4a.xsd">
  <book ISBN="m789">
    <title>English</title>
    <author title="mr" phone="9897236275" email="rajesh@gmail.com">
      <first_name>Rajesh</first_name>  
      <middle_name>Kumar</middle_name>  
      <last_name>Khatiwada</last_name>
    </author>
    <author title="mrs" phone="9656717815" email="shristi@gmail.com">
      <first_name>Shristi</first_name>  
      <middle_name>Maya</middle_name>  
      <last_name>Tandukar</last_name>
    </author>
    <author title="ms" phone="9841236154" email="krisha@gmail.com">
      <first_name>Krisha</first_name>  
      <middle_name>Laxmi</middle_name>  
      <last_name>Basnet</last_name>
    </author>
    <page_no>345</page_no>
    <price currency="NPR">500</price>
  </book>
</books>
