=== Suhana-shakya/XML-lab/Number3a.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="songs">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="song" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="singer" type="xs:string"/>
              <xs:element name="compose_by" type="xs:string"/>
              <xs:element name="length" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Suhana-shakya/XML-lab/Number3.xml
<?xml version="1.0" encoding="UTF-8"?>
<songs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Number3a.xsd">
  <song>
    <name>Rewrite the stars</name>
    <singer>Annie Marrie</singer>
    <compose_by>James Arthur</compose_by>  
    <length>4 min</length>
  </song>
  <song>
    <name>Aparibhasit</name>
    <singer>Swapnil Sharma</singer>
    <compose_by>SWAR</compose_by>  
    <length>5 min</length>
  </song>
  <song>
    <name>We can't be Friends</name>
    <singer>Ariana Grande</singer>
    <compose_by>Ariana</compose_by>  
    <length>5 min</length>
  </song>
  <song>
    <name>Birds of a Feather</name>
    <singer>Billie Eilish</singer>
    <compose_by>Billie</compose_by>  
    <length>4 min</length>
  </song>
</songs>
